// www/src/pages/Root/Index.vue
<script setup lang="ts">
import { router } from '@inertiajs/vue3';

let props = defineProps<{
  timestamps: Array<[boolean, number]>;
}>();

let deleteAll = () => {
  router.delete(`/timestamps/`, { preserveScroll: true })
}

let trash = (id: any) => {
  router.delete(`/timestamps/${id}`, { preserveScroll: true })
}

let add = () => {
  router.post(`/timestamps/`, {}, { preserveScroll: true })
}

let update = (id: any) => {
  router.patch(`/timestamps/${id}`, {}, { preserveScroll: true })
}

let validate = (bool: Boolean) => {
  let result = '';

  if (bool == true) {
    result = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle"> <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path> <polyline points="22 4 12 14.01 9 11.01"></polyline> </svg>`
  } else {
    result = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-circle"><circle cx="12" cy="12" r="10"></circle></svg>`
  }
  return result;
}

document.addEventListener("visibilitychange", function() {
  if (document.visibilityState === "visible") {
  router.reload({ preserveScroll: true })
  }
});

</script>

<template>
  <main>

    <!-- Navigation -->
    <div class="navigation--container">
      <div class="navigation--item">
        <button @click="deleteAll">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"> <polyline points="3 6 5 6 21 6"></polyline> <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path> <line x1="10" y1="11" x2="10" y2="17"></line> <line x1="14" y1="11" x2="14" y2="17"></line> </svg>
        </button>
      </div>

      <!-- <div class="navigation--item">
        <button @click="editData()">Edit</button>
      </div> -->

      <div class="navigation--item">
        <button @click="add">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"> <line x1="12" y1="5" x2="12" y2="19"></line> <line x1="5" y1="12" x2="19" y2="12"></line> </svg>
        </button>
      </div>

    </div>


    <!-- List -->
    <div class="list--container">
    <!-- Headline -->
    <h1 class="unselectable">Timestamps</h1>

      <div class=".unselectable list--item" v-for="timestamp in props.timestamps">

        <div><button v-html="validate(timestamp[0])" @click="update(timestamp[1])"></button></div>
        <div>{{ timestamp[1] }} ms</div>
        <button @click="trash(timestamp[1])" class="delete-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"> <polyline points="3 6 5 6 21 6"></polyline> <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path> <line x1="10" y1="11" x2="10" y2="17"></line> <line x1="14" y1="11" x2="14" y2="17"></line> </svg>
        </button>

      </div>

    </div>

  </main>
</template>




<style>
main {
  font-family: Arial, Helvetica, sans-serif;
  position: relative;
}

body {
  margin: 0;
  background-color: #F2F2F7;
  padding-top: 6px;
  padding-left: 18px;
  padding-right: 18px;
}

.unselectable {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

h1 {
  margin-top: 6px;
  margin-bottom: 6px;
}

button {
  all: unset;
}

button:focus {
  all: unset;
}

.navigation--container {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  display: flex;
  justify-content: space-between;
  background-color: #F2F2F7;
}

.navigation--item {
  padding: 12px;
}

.list--container {
  margin-top: 40px;
  display: flex;
  flex-direction: column;
  gap: 1px;
}

.list--item {
  background-color: white;
  padding: 10px;
  border-radius: 4px;

  display: flex;

  gap: 12px;
  font-size: 18px;

  justify-content: space-between;

  gap: 24px;

  align-items: center;
}
</style>

// www-svelte/src/pages/Root/Index.svelte
<script lang="ts">
  import { router } from "@inertiajs/svelte";
  import { onMount } from "svelte";

  export let images: any;

  const getData = () => {
    location.reload();
  };

  const takePicture = () => {
    router.get(`/takePicture`, { preserveScroll: true });
    getData();
  };

  const deletePicture = (imageId) => {
    // console.log("Bild löschen", imageId);
    router.delete(`/${imageId}`, { preserveScroll: true });
    getData();
  };

  let loadImages = async () => {
    const imageContainer = document.getElementsByClassName("img-container")[0];

    await new Promise((resolve) => setTimeout(resolve, 0)); // Warte kurz, um der Seite Zeit zum Rendern zu geben

    for (let index = 0; index < images.length; index++) {
      const image = images[index];
      const imageDiv = imageContainer.children[index];

      let imageURL = `data:image/png;base64,${image.image}`;
      imageDiv.style.background = `url(${imageURL})`;
      imageDiv.style.backgroundPosition = "center";
      imageDiv.style.backgroundSize = "cover";
    }
  };

  onMount(() => {
    loadImages();
  });
</script>

<header />

<main>
  <h1>Camera - Feature</h1>
  <button on:click={takePicture}>Kamera öffnen</button>
  <button on:click={getData}>Update</button>

  <div class="img-container">
    {#each images as image}
      <div class="img-item">
        <button on:click={() => deletePicture(image.id)} class="delete-button">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="white"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="feather feather-trash-2"
          >
            <polyline points="3 6 5 6 21 6" />
            <path
              d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
            />
            <line x1="10" y1="11" x2="10" y2="17" />
            <line x1="14" y1="11" x2="14" y2="17" />
          </svg>
        </button>
      </div>
    {/each}
  </div>
</main>

<style>
  main {
    font-family: system-ui, -apple-system, sans-serif;
  }

  .img-container {
    margin: 5px;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    gap: 3%;
    row-gap: 10px;
  }

  .img-item {
    width: 31%;
    height: 150px;
    object-fit: cover;
    border-radius: 4px;
    position: relative;
  }

  button {
    all: unset;
    padding: 14px;
    font-family: system-ui, -apple-system sans-serif;
    font-size: 18px;
    background-color: black;
    color: white;
    border-radius: 8px;
  }

  .delete-button {
    all: unset;
    position: absolute;
    top: 5px;
    right: 5px;
    padding: 5px;
    border-radius: 4px;
    background-color: black;
  }
</style>
